# .github/workflows/run-scraper.yml

name: Scrape TKT.GE Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # --- ADD THIS LINE ---
          playwright install --with-deps chromium

      - name: Run the scraper
        run: python api_scraper.py

      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update scraped event data"
          file_pattern: tkt_events_from_api.json
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
